# Generated by Django 4.2.10 on 2024-02-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_yourmodel_videomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
