# Generated by Django 4.2.10 on 2024-02-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_videomodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('discription', models.TextField(blank=True, max_length=200)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='discription',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
