# Generated by Django 4.2.10 on 2024-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.CharField(blank=True, max_length=100)),
                ('discription', models.TextField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
