# Generated by Django 4.2.10 on 2024-02-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='VideoModel',
        ),
    ]
